[tool.poetry]
name = "connecthole"
version = "0.1.0"
description = ""
authors = ["Eelco Wesemann <6771014+sgaduuw@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
